---
version: "3.9"

services:
  db:
    image: postgres:13.3
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 65
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    # ports:
    #   - "5434:5432"

  backend:
    build:
      context: .
    image: vk_hack-misis_tolerant-backend
    depends_on: # healthy db
      db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - "6948:8000"

volumes:
  db: